pub mod activity;
pub mod antigravity;
pub mod claude_web;
pub mod cursor;
pub mod cli;
pub mod costs;
pub mod dock;
pub mod focus;
#[cfg(target_os = "macos")]
pub(crate) mod macos;
pub mod obsidian;
pub mod providers;
pub mod status;
